### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by lepp12** [DS4PS/cpp-527-fall-2020#34]
One of the links in the Lab 5 instructions is not working.

In  the **Add Page and Update Navigation** section, the link `getting started page` returns a 404 error.

The link points to `https://github.com/daattali/beautiful-jekyll/blob/gh-pages/getstarted.md`

That link works fine up to `https://github.com/daattali/beautiful-jekyll` but can't seem to find the next location of `blob`. I thought maybe that was supposed to say `https://github.com/daattali/beautiful-jekyll/blog` but that didn't work either...

I've searched in the master branch, but still can't seem to find the **getstarted.md**

Am I missing something?

**Comment by nicolehillsmall** [comment]
I believe getstarted is the original author's README

**Comment by lepp12** [comment]
@nicoletriestocode That makes a bit more sense, thank you so much! I'm going to go with that, unless @lecy weighs in with a different approach?

Thanks again!

**Comment by lecy** [comment]
Hi All - I am realizing that they have made major updates to the Beautiful Jekyll shell. It looks like they are trying to turn it into more of a paid service. The goal was to find a simple website template so that you can focus on configuration and settings instead of content to get a feel for how the parts work together. 

You are free to use the Beautiful Jekyll template if you have already started.

But let me offer these alternatives - feel free to fork these sites as your starting point and build from their templates instead of from the main Beautiful Jekyll repository. 

----

[Tea Time Artist Blog](https://melyanna.github.io/)

Repository: https://github.com/Melyanna/Melyanna.github.io

[Professor Derek Ogle Personal Site](https://derekogle.com/aboutme)

Repository: https://github.com/droglenc/droglenc.github.io

---

*The last one provides some examples of templates for galleries for people and projects so you can see the adaptation of the site.*

[R Epidemics Consortium](https://www.repidemicsconsortium.org/)

Repository: https://github.com/reconhub/reconhub.github.io

**Comment by lecy** [comment]
The last one provides a great example of templating content. 

You can see the gallery of consortium members on their ["People" page](https://www.repidemicsconsortium.org/people/):

![image](https://user-images.githubusercontent.com/1209099/94193132-cf84e800-fe64-11ea-9a22-d25bf64bcfdb.png)

If you inspect this [page MD file](https://raw.githubusercontent.com/reconhub/reconhub.github.io/master/peopleold.md), the entire page looks like this: 

```
## Community

RECON is a group of people sharing their time and expertise to lead, facilitate, advise, and promote the development of analysis tools for outbreak response using the [R software](https://www.r-project.org/). The list of people below is growing as we are recruiting more members. See [this page](../join) to join us.

{% include list-circles.html items=page.people-list %}


## Advisory board

We are extremely lucky to have the following people supporting and guiding our efforts:

{% include list-circles.html items=page.board-list %}


## Administration

RECON also benefits from some outstanding administrative support from the following people:

{% include list-circles.html items=page.admin-list %}
```

But the data for individual members is just a table in the YAML header. 

```
board-list:
  - name: Gregory Armstrong
    img: /img/people/gregory-armstrong.jpg
    desc: Director of the Advanced Molecular Detection initiative, with extensive experience in epidemiology and outbreak response at CDC, Atlanta, USA.
    website: http://www.cdc.gov/amd/
    url: http://www.cdc.gov/amd/
    twitter: https://twitter.com/CDC_AMD
  - name: Gabor Csardi
    img: /img/people/gabor-csardi.jpg
    desc: Computer scientist with a strong background in statistics and network theory, Gabor is a prominent member of the R community who develops and contributes to a number of major packages such as <i>igraph</i>, <i>roxygen</i> and <i>R6</i>. Mango Solutions, Chippenham, UK.
    website: http://gaborcsardi.org/
    url: http://gaborcsardi.org/
    github: http://github.com/gaborcsardi
    twitter: http://twitter.com/gaborcsardi
  - name: Christl Donnelly
    img: /img/people/christl-donnelly.jpg
    desc:  Professor of Statistical Epidemiology, Fellow of the Royal Society, Christl has extensive experience in epidemics analysis and emergency outbreak response. Imperial College London, UK.
    website: http://www.imperial.ac.uk/people/c.donnelly
    url: http://www.imperial.ac.uk/people/c.donnelly
```

If you navigate to the _includes folder you can find the [**list-circles.html**](https://github.com/reconhub/reconhub.github.io/blob/master/_includes/list-circles.html) file, which contains the template for each member and a loop to generate a whole table of members:

![image](https://user-images.githubusercontent.com/1209099/94193663-78cbde00-fe65-11ea-9408-8da7a4b49b7c.png)

You don't need to understand this HTML page to see how the site works. You can hire someone for $25 to make this single template for you. Just send a link to a page design you like and ask them to create and HTML template using liquid tags. 

You can see examples of these sorts of transactions at **FIVERR** - a marketplace for programming and design services. 

https://www.fiverr.com/hire/jekyll

You might be amazed at how cheap it can be to contract out **part of** of the job if you know what to ask for. 

The goal in building these pages is to know enough to set up a site, configure the settings, and maintain content. Then just hire experts to do some of the customization that requires more knowledge of web programming. Or similarly, when designing custom reporting templates to automate tasks in your organization, if you search around and find a report style you like you can very cheaply find people to build that template for R Markdown. 

![image](https://user-images.githubusercontent.com/1209099/94194089-0d364080-fe66-11ea-9175-4850090b7e63.png)
