### ISSUE TITLE
Lab 05 table demo pic was there...and now it's not

### ISSUE THREAD

**Issue by krbrick** [DS4PS/cpp-527-fall-2020#38]
my files and folders are all linked appropriately and in the right place...yesterday this pic was visible and now it is gone. Yesterday evening I at least had a blue question mark for a bad file, but now there is nothing. Any advice?
https://krbrick.github.io/lab05.io/table-demo/
https://github.com/krbrick/lab05.io/blob/master/table-demo.md
```
---
layout: liquid-table
title: 'amiright?'
reynolds:
  strengths:
  - good father
  - funny
  - dated alanis morissette
  weaknesses: 
  - singing
  - green lantern movie
  - tennis backhand 
gosling:
  strengths: 
  - builds houses
  - is a real boy
  - never dated alanis morissette
  weaknesses: 
  - micky mouse club
  - cries a lot
  - not ryan reynolds
---


![]({{site.url}}/assets/img/gallery-1481570039-gettyimages-629207774.jpg)

![]({{site.url}}/assets/img/ryan-v-ryan.jpg)  


## Lorem Ipsum

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 
```
